"use client";
// import './globals.css'
import { Fira_Code, Inter, Raleway } from "next/font/google";
import "@/scss/index.scss";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });
const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <style jsx global>{`
        :root {
          --raleway: ${raleway.style.fontFamily};
          --fira-ode: ${firaCode.style.fontFamily};
        }
      `}</style>
      <html lang="en">
        <title>gyeNyame</title>
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
